### ISSUE TITLE
Try/catch in _functions.cfm getLineMets() is masking errors

### ISSUE THREAD

**Issue by bdw429s** [dapywell/cfperformanceexplorer#3]
Is there a reason for the try/catch in the `getLineMets()` function?  It is masking errors in the Java code which just makes debugging harder.  If the app errors, I'd expect the app to notify me of the failure instead of just displaying empty metric data which is misleading.

**Comment by Cumminsc9** [comment]
Split up the Try/Catch so depending upon the error a different exception is displayed. Added improved metric validation to check if the metrics exist before displaying the warning.
